// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHhti4mjgZcPD6DpGxqCYynTdf1Th8nak',
    appId: '1:270979632727:web:19d3a7e2f1d6349d2a9d12',
    messagingSenderId: '270979632727',
    projectId: 'barber-flutter-app',
    authDomain: 'barber-flutter-app.firebaseapp.com',
    storageBucket: 'barber-flutter-app.appspot.com',
    measurementId: 'G-9KVZG5NMSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA02w9aLQMHXCEewmbEoxwMbI3scMgRv50',
    appId: '1:270979632727:android:ace80e3c13300f532a9d12',
    messagingSenderId: '270979632727',
    projectId: 'barber-flutter-app',
    storageBucket: 'barber-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9gbS7WwLF9h0kw9FVZmF4lUwalRoATCY',
    appId: '1:270979632727:ios:9fdc784c17843d7b2a9d12',
    messagingSenderId: '270979632727',
    projectId: 'barber-flutter-app',
    storageBucket: 'barber-flutter-app.appspot.com',
    iosBundleId: 'com.example.barber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9gbS7WwLF9h0kw9FVZmF4lUwalRoATCY',
    appId: '1:270979632727:ios:9fdc784c17843d7b2a9d12',
    messagingSenderId: '270979632727',
    projectId: 'barber-flutter-app',
    storageBucket: 'barber-flutter-app.appspot.com',
    iosBundleId: 'com.example.barber',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHhti4mjgZcPD6DpGxqCYynTdf1Th8nak',
    appId: '1:270979632727:web:5a9003478f50ebe22a9d12',
    messagingSenderId: '270979632727',
    projectId: 'barber-flutter-app',
    authDomain: 'barber-flutter-app.firebaseapp.com',
    storageBucket: 'barber-flutter-app.appspot.com',
    measurementId: 'G-7Q5FEZNK5B',
  );
}
